hash-format = "sha256"

[[files]]
file = "config/SkipTransitions.properties"
hash = "65c60525a8520ef94fb060b187bc73dd57128c77d865d5e417538823eb97c679"

[[files]]
file = "config/capes.json5"
hash = "53a832e6bf982fcc4935c9c42acc689bb95dfa6025c394ff0b190c15fc31121d"

[[files]]
file = "config/customsplashscreen.json5"
hash = "536f50bca2e98c81a7fef4a87ba4e545aebae9963f3652eaa5f1169b440a4deb"

[[files]]
file = "config/customsplashscreen/background.png"
hash = "fa862b02d5b72b939d467123b42991086527d9a0ef117d8f3df3f21703593a07"

[[files]]
file = "config/customsplashscreen/mojangstudios.png"
hash = "27b2ea2946ca5b00841ce7d1813b42dfb7e36b12ad50c7c9bea09053ac226cf3"

[[files]]
file = "config/customsplashscreen/mojank.png"
hash = "ebe2b6434c2d4a0c3990c46acf77464bb7ce1a5ac83c6b495bccadc1f1a048a7"

[[files]]
file = "config/customsplashscreen/progressbar.png"
hash = "e2e0555e30fd677e05570551f36d3a95fd844dcadc62b15e4f901c3442a5e3c7"

[[files]]
file = "config/customsplashscreen/progressbar_background.png"
hash = "6e2fa0adee9638b3e8f36e75ad048f0abb0de2d06b591961c6b2aff943fd46f2"

[[files]]
file = "config/durabilityviewer.json"
hash = "f603891b4acc69f58ce40dd87cf23d2fb441a144563d6a7a04233fdbb0c691cd"

[[files]]
file = "config/inspecio.json"
hash = "7a88fa204fa6c32883ee9d6c9705a83ebc5f425c3c07d38f9aadce2d544d134d"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "4e527f98146bb7caa91cf864f99becd27042675b73f3ae77b99ce369c2c0ebd9"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b99f8b297b9429f5185c84805d1a67f650bba836cf83c6c9d81b275261169672"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "00d8a4cdf1fecfb1b471e21546d7817bddb252aab3ea72d167ae690935a3847f"
metafile = true

[[files]]
file = "mods/bedrockskinutility.pw.toml"
hash = "8399acf40ad93ed00f1bc89aec10d65bd9f863f27ed8a3539694d7c64cb38eeb"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "97b90825ea397eae1dc108b5a9257e3065feacb553e72c019fba62495a72c1d0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "2b9d778f845e30e9111c5b02f8fc68c797ad39e2a79c7e9d88ab54fa133b100b"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "3b2c1ac53b3aed8e5d0a20ed50a663e8c24948216ab93acd4135c69b3c2fa1e1"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "379a2c793f5f3f31b06581ba86de7ae4f32f401b466fb4dd684d6a7596df2fbf"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "b46ae91063839b3aaa7a863f69586e00883a6c98b2959005eaff27a459aa5d82"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "5e289f7ef37b75b340dde02ee3a11a92ba6d4f045fd4f67eb3647b18cf51f739"
metafile = true

[[files]]
file = "mods/customsplashscreen.pw.toml"
hash = "958edcd57dbb9f923080ac1119c8cf76fd4a7951c8cda5952117fb17243a5d94"
metafile = true

[[files]]
file = "mods/dcch.pw.toml"
hash = "f811170d884fbbe2ccbd8e5c42137eb490d0116255878f5b53336efafcb2877c"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
hash = "c02eabded8af6a2282b4b44aab15206f198d44be3df21dd93ec8a8d4824ac32f"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "f52293cc81b07666eeee3bfcf5f34039e2d2bc64cd22416b5cbdb554eec17a0e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "855e5f89a1c2d225f10927dd9bdd06aaffbc0c59b6d2c525460db6f1c9742ad5"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
hash = "d614e471929c4906f85ba776600e0cfa9b0d958ce55121efd49c9ffd4ff00a04"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "8e91eac9da646c5458d00fb68ccf0887bf815947ef549cb19abebe1e6cec5c72"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "ac0a425f01b57603d143e65eebba8b53078474c61f8f0a9a35ab2bbd7ed3a931"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "0c7c2c37874d5341092e6c63f95f4f95d7fa804e1c28ea9e83c1ed5115dcf12f"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "ea71f8679ff436996c48a8ca94b083740acd82a268e79618f7823f5f507b187f"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.pw.toml"
hash = "4191daf9db203945cd504e0489ce9008f718bb69fa8ce36cf3847ab28f05355c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "eefcd81493fa26fa8135cf85495cbfb52127aa43667c5a4faea27d16d7bb2191"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "1cefb097ea4012055582060d6939a7928f359a514f01dde8cbf0edb58a13d388"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a348ec1aec5a10f7235d6741e08aea583e042049eded3d6eafd97a0688a891c0"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "b893248407cbc155a5182b151acf50df075cef08bd0a9470c222425e8e47a809"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a2bb983e5dffe95d1f92ee19a099ed214f9b3d39c4e9f8eb5991a1a3c7735b45"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "443104f3ae619456aefa8eaabf9dbfba4c0a227435fc7c6e2f4c89370bb6786d"
metafile = true

[[files]]
file = "mods/lmcm.pw.toml"
hash = "38d08909252762ddc677e522f321e98295072b963ced1f357aeb7d1f0070032d"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "8fca044c06687f1e0f645ea179fa96a73abe84c7e4e4c982633868c150553732"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "90cfb6a5fdd929c94421cd0674e2af68089e33a8e3965d7dec723ab00df2e94a"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d48418bcd2fa81939864dc15e2230909b945c9b618064f16cc11f9b4db581740"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "a067a3a38a6df8bf4440edc13ad29e22adf31041858c4fc4aee991c0f0e87263"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
hash = "d66a3e2d8bd4e887e659460567a311f2a184a191be157804c757890f92d143d4"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8cc78f5916f31b9d350f75d5fd0dad8df9662066763324b36abf6eaced24aef5"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "b054c54c9732cf012526bcb529c189f808692c17aa29e306444a2110df43d38d"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "014566a9d16177ef1499864718b28090b5ac254e3e910a2cea67b911b56f3e5a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ae4b4112db3f14bcb9e8dc10ea06e83d84bff4d9ad2a3dfd74533c1256b98218"
metafile = true

[[files]]
file = "mods/searchable-containers-retraversal.pw.toml"
hash = "5de1a8776f9235a58667ef4dec3c9f8a3847da4fb6e4a5a1999021b719649ee4"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "2fa2a85756bccff04668147d557e77394a583604ab2eae258311cff9e0864512"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "3f2148f425622b9226aac1a5ea41f6613f9fdc0f484eadd72d30714ab0a73895"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "44ff9922b86d4c7f8cd74da120536f0670dfa0584da0b03b7d53cd5d82690f2e"
metafile = true

[[files]]
file = "mods/vtdownloader.pw.toml"
hash = "23c73f09141fa81161872c7549725eefc0ee85187bcc86e50d2513c17eeb71bf"
metafile = true
