hash-format = "sha256"

[[files]]
file = "config/SkipTransitions.properties"
hash = "65c60525a8520ef94fb060b187bc73dd57128c77d865d5e417538823eb97c679"

[[files]]
file = "config/durabilityviewer.json"
hash = "f603891b4acc69f58ce40dd87cf23d2fb441a144563d6a7a04233fdbb0c691cd"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "4e527f98146bb7caa91cf864f99becd27042675b73f3ae77b99ce369c2c0ebd9"

[[files]]
file = "mods/bedrockskinutility.pw.toml"
hash = "8399acf40ad93ed00f1bc89aec10d65bd9f863f27ed8a3539694d7c64cb38eeb"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "5e206d6a7aa7744a3322189386a7e3c4315df2dd8a1d3a648bcde498a7a3c934"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "90de023b54d15536a49e98bd4b79319940381bad60e8ca9798a4f5468b9b156f"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "f06d2023edfd505850b00538fad3e4963fd0b88e8385e1610a3cbe258a806d75"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "2b9d778f845e30e9111c5b02f8fc68c797ad39e2a79c7e9d88ab54fa133b100b"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "3b2c1ac53b3aed8e5d0a20ed50a663e8c24948216ab93acd4135c69b3c2fa1e1"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
hash = "c02eabded8af6a2282b4b44aab15206f198d44be3df21dd93ec8a8d4824ac32f"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "6cb34219f7edaae938e9f4edabe1ee15742c6784d59dc97fc3e6df4a5e24d850"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "855e5f89a1c2d225f10927dd9bdd06aaffbc0c59b6d2c525460db6f1c9742ad5"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c57ab7e92b672af93416304950b083d0b20aabe41af61d0993292dfef80744bf"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "ac0a425f01b57603d143e65eebba8b53078474c61f8f0a9a35ab2bbd7ed3a931"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.pw.toml"
hash = "4191daf9db203945cd504e0489ce9008f718bb69fa8ce36cf3847ab28f05355c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "b5ecdce430ae016b791f415ef55f6740dcfd422cdb24c2ea78e4ec677cc7921e"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "1cefb097ea4012055582060d6939a7928f359a514f01dde8cbf0edb58a13d388"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e516d6d036f6d407a793c3b9a1fc5a8a817b05c9dc9d8677003fb0a512b2bf6f"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a2bb983e5dffe95d1f92ee19a099ed214f9b3d39c4e9f8eb5991a1a3c7735b45"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "443104f3ae619456aefa8eaabf9dbfba4c0a227435fc7c6e2f4c89370bb6786d"
metafile = true

[[files]]
file = "mods/lmcm.pw.toml"
hash = "1fa554070ef9ea4fd267bcbe4633cd95edd1ceab0e04d03197fc56349e104bd4"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "dc1f47a526f2264dc215437a81668d54c084d5beaaa6cbf6e284b88a59af88b5"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "666ebc5403d60bbaea03d0c82e83e3f1fa75756a77501dab3ec2a7b7bf2b24dd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d48418bcd2fa81939864dc15e2230909b945c9b618064f16cc11f9b4db581740"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "91e24178f86243b32a8516ceefd1f21b054d7c963e44f274ddfede8d8d41c027"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8cc78f5916f31b9d350f75d5fd0dad8df9662066763324b36abf6eaced24aef5"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "d4aca8f69489a3df5cbd9793e3f74f107b1b8da477bd21b6125db6d4b182cf92"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b4d8e22f7916c1a2e8be07b708cd02d16bd730e382bb7ca36a615cf3e6782940"
metafile = true

[[files]]
file = "mods/skiptransitions.pw.toml"
hash = "1e3fdc90ca29630ec56ca281fe6900d8331e96204d1e08b08f4a449d0efa0ca5"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8bdc3c1b5079b7fbe89f995d1a100e1df8dcf47e73ef089abf444ecc8e320527"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "0024debffc8fa9ace160b5115c333061c5a678872dcc53b44185d27ac4850f51"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "1019a95bc491e51612313e91338271ca19fc1e572b9f48a2f9bfd3d5fbf88b71"
metafile = true
