hash-format = "sha256"

[[files]]
file = "config/SkipTransitions.properties"
hash = "65c60525a8520ef94fb060b187bc73dd57128c77d865d5e417538823eb97c679"

[[files]]
file = "config/capes.json5"
hash = "53a832e6bf982fcc4935c9c42acc689bb95dfa6025c394ff0b190c15fc31121d"

[[files]]
file = "config/customsplashscreen.json5"
hash = "536f50bca2e98c81a7fef4a87ba4e545aebae9963f3652eaa5f1169b440a4deb"

[[files]]
file = "config/customsplashscreen/background.png"
hash = "fa862b02d5b72b939d467123b42991086527d9a0ef117d8f3df3f21703593a07"

[[files]]
file = "config/customsplashscreen/mojangstudios.png"
hash = "27b2ea2946ca5b00841ce7d1813b42dfb7e36b12ad50c7c9bea09053ac226cf3"

[[files]]
file = "config/customsplashscreen/mojank.png"
hash = "ebe2b6434c2d4a0c3990c46acf77464bb7ce1a5ac83c6b495bccadc1f1a048a7"

[[files]]
file = "config/customsplashscreen/progressbar.png"
hash = "e2e0555e30fd677e05570551f36d3a95fd844dcadc62b15e4f901c3442a5e3c7"

[[files]]
file = "config/customsplashscreen/progressbar_background.png"
hash = "6e2fa0adee9638b3e8f36e75ad048f0abb0de2d06b591961c6b2aff943fd46f2"

[[files]]
file = "config/durabilityviewer.json"
hash = "f603891b4acc69f58ce40dd87cf23d2fb441a144563d6a7a04233fdbb0c691cd"

[[files]]
file = "config/inspecio.json"
hash = "7a88fa204fa6c32883ee9d6c9705a83ebc5f425c3c07d38f9aadce2d544d134d"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "b5fa9e74d4bc37b92581ce989d9a0599282db9402772635e06f2c27669221f1a"

[[files]]
file = "config/mousewheelie.hjson"
hash = "dda85738e0e40ddeecafdf47402d4bb6e1972304631fc08d7827edf14c6c3dcb"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "00d8a4cdf1fecfb1b471e21546d7817bddb252aab3ea72d167ae690935a3847f"
metafile = true

[[files]]
file = "mods/bedrockskinutility.pw.toml"
hash = "8399acf40ad93ed00f1bc89aec10d65bd9f863f27ed8a3539694d7c64cb38eeb"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "e8cd685b609577ab23e2a55ec3273a1ff9475daef52f0999b2c5d27f7c795f5c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "01ab4442937c2d1f582722d139c0d02b3fc36c61a3eeebb4e81bd5256b7d8470"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "eaba2f41f04c306118190beb2a2bf4a44263e0196a106b9c8a9bfddff038afab"
metafile = true

[[files]]
file = "mods/cleardespawn.pw.toml"
hash = "8692d52811bcd5ae4e520c29ed2f4567063157551df721ce71d7f3008e693662"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "1a4c9d83b0709fd2f91814eb67f81e19bb1493315c42cb65efe911d0f34c5a13"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c06e098c6d6eda6da4492e4a8dff1796e6081bbd30f487ffb89e1ed3c485e805"
metafile = true

[[files]]
file = "mods/custom-splash-screen.pw.toml"
hash = "23e3c4cb4e2ee0ed4cd1d9a8e1960578cf3e49839813c7930c4809aba304a1f7"
metafile = true

[[files]]
file = "mods/dcch.pw.toml"
hash = "f811170d884fbbe2ccbd8e5c42137eb490d0116255878f5b53336efafcb2877c"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
hash = "84c3fa8f432a1f7d8692e7a52f5c4a7b60c5c215a1329af48df76544e72b90d6"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "f52293cc81b07666eeee3bfcf5f34039e2d2bc64cd22416b5cbdb554eec17a0e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
hash = "d614e471929c4906f85ba776600e0cfa9b0d958ce55121efd49c9ffd4ff00a04"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c985bc9064cc29094fdfd59a037baa1523778cc2a9e5665c3f1b6ca0efe6a543"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "00960cdd63d16c9a2ca9f1e3a9c3aa79d789c0284fb19091ba4b8841a7f5def5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "61c9106111d0e22864a9a68f678faa5094fc1cbdfdc50a72d3898b1bc217a032"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.pw.toml"
hash = "4191daf9db203945cd504e0489ce9008f718bb69fa8ce36cf3847ab28f05355c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "373a56d7f4fb25661a0585492f7ea490e7613f1191e588fec08782438d52e1fd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b27773505b8fcfb4dd88dbc5b3cea9c5dfb3d9fac0cb4d91f4b8ccbde7a275ad"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "b893248407cbc155a5182b151acf50df075cef08bd0a9470c222425e8e47a809"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "77e9a02e09ec5a0d6682e5f448953048d99e36da299d92627044aff0828798e3"
metafile = true

[[files]]
file = "mods/lmcm.pw.toml"
hash = "a9610856c69c4fddec08decd2b88969d06427138704c8a34e52ffe53783e0107"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "13cf5c8363c82bbd368b0cc7bc7a779bfabbee0a552471a976f41af58e6df1b6"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "133ec9cccfd238b4ce6bd5b95dcf70a9603c86d7c22a347c483925b34425fbb5"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "509e5fceb5ca7626d953238a57de458e73798464a1bd878df6ca956eedff2781"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1aa7510ec1a3994273a20f8b341f676583b9ede2eaea3badd46deb7178d92a6c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "17dc4f0920a4089790c8d13abff319a5e83f2aea7a06cdd3cc79699fa5ccdc8a"
metafile = true

[[files]]
file = "mods/numeral-ping.pw.toml"
hash = "5cdb03823da80cc246bf744cbd758cd6f2004c94f44063cd2a46ba769f648e01"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "8cc78f5916f31b9d350f75d5fd0dad8df9662066763324b36abf6eaced24aef5"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "91f5cb8e796aa7c8407f89c9da255678e71ae588b622c4c848c0f70d803dc5b7"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "a11bee072c28f106a16bda9987613f5a361f26215cf91c75b4210c07b2cab4ef"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/searchable-containers-retraversal.pw.toml"
hash = "5de1a8776f9235a58667ef4dec3c9f8a3847da4fb6e4a5a1999021b719649ee4"
metafile = true

[[files]]
file = "mods/simple-shulker-preview.pw.toml"
hash = "e48b9bd2c6543cb91f83338cbe01647a3010b3a6a92c9065d65816bbbdee9a68"
metafile = true

[[files]]
file = "mods/skip-transitions.pw.toml"
hash = "2fa2a85756bccff04668147d557e77394a583604ab2eae258311cff9e0864512"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "be68ef606c339bbb22f2b812db1e5264d9e3335befc0c348d4dc91a8a3e72e17"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "bde468f83e589ec78b996898447516df1cfe8ced8186caf6a23b7c3933f9b22d"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "1fa60ac650ff3c38048d95b97366fcbf2a42d5dd92f1dd93b55e0cf58d2248e7"
metafile = true

[[files]]
file = "mods/vtdownloader.pw.toml"
hash = "b935d2b958f96006d9f39fe585a240cbcc2701fe437c49e6f7c539a1ade0bc90"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "afc5f3bf4cae41e848070a109287bc6607c2f46045fc452da5d43189358adcb6"
metafile = true

[[files]]
file = "readme.md"
hash = "dbf53ffad6866cbc9fded6271396ae2173cbf190178e5244ceac7b7a9a249e99"
