name = "Loyal MC Survival Modpack"
author = "Mr_SpiderCat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "738e8ea6cf9f9bf41ddbd57b68d93e13c321f6c6a287b9b5aea728189529812b"

[versions]
minecraft = "1.19"
quilt = "0.17.0"
