name = "Loyal MC Survival Modpack"
author = "Mr_SpiderCat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b96a51ca37d4fc24df51aab211cd629d6a52e37a2d1f7551f51f341a24648ed3"

[versions]
minecraft = "1.19"
quilt = "0.17.4"
